### ISSUE TITLE
Error in db-snapshot-cleanup.py

### ISSUE THREAD

**Issue by veerbahadur** [cmabastar/RDSmanualbackups#1]
db-snapshot-cleanup.py is throwing below error:

Traceback (most recent call last):
  File "db-snapshot-cleanup.py", line 42, in <module>
    os.remove('./rds-snapshots/' + dbs_id)
NameError: name 'os' is not defined

Basically this script is not importing "os". To fix this just add this line
import os

**Comment by cmabastar** [comment]
thanks, I added the fix.
